// Engine configuration constants.
//
// Source of truth: hexo.toml at workspace root.
// Generated by build.rs at compile time. See SPEC_CONFIG.md.
//
// Do not put magic numbers in other modules — add them to hexo.toml and
// reference them from here.

include!(concat!(env!("OUT_DIR"), "/config_generated.rs"));
